# Generated by Django 5.0.6 on 2024-06-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('adhaar_no', models.IntegerField(unique=True)),
                ('current_plan', models.CharField(max_length=100)),
            ],
        ),
    ]
