# Generated by Django 5.0.6 on 2024-06-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='adhaar_no',
            new_name='aadhaar_no',
        ),
    ]
