# Generated by Django 5.0.6 on 2024-06-30 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_adhaar_no_customer_aadhaar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhaar_no',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
